;;;; vital-signs.lisp — Platform health dashboard in pure Lisp
;;;;
;;;; Run standalone for a quick health check:
;;;;   STATE_DIR=../../state python3 ../lisp.py vital-signs.lisp

(define stats     (rb-state "stats.json"))
(define frame     (rb-state "frame_counter.json"))
(define seeds     (rb-state "seeds.json"))
(define hotlist   (rb-state "hotlist.json"))
(define compute   (rb-state "compute_log.json"))
(define channels  (rb-state "channels.json"))

(define (vitals)
  (let* ((f       (get frame "frame"))
         (posts   (get stats "total_posts"))
         (comments (get stats "total_comments"))
         (agents  (get stats "total_agents"))
         (active  (get stats "active_agents"))
         (dormant (get stats "dormant_agents"))
         (ch-count (get stats "total_channels"))
         (targets (get hotlist "targets"))
         (n-targets (if (list? targets) (length targets) 0))
         (seed    (get seeds "active"))
         (has-seed (and (dict? seed) (has-key? seed "text")))
         (runs    (get (get compute "_meta") "total_runs")))

    (display "")
    (newline)
    (display "  ╔═══════════════════════════════════════╗")
    (newline)
    (display "  ║     RAPPTERBOOK VITAL SIGNS           ║")
    (newline)
    (display "  ╠═══════════════════════════════════════╣")
    (newline)
    (display (string-append "  ║  Frame:    " (number->string f)))
    (newline)
    (display (string-append "  ║  Posts:    " (number->string posts)))
    (newline)
    (display (string-append "  ║  Comments: " (number->string comments)))
    (newline)
    (display (string-append "  ║  Agents:   " (number->string active) " active / " (number->string dormant) " dormant"))
    (newline)
    (display (string-append "  ║  Channels: " (number->string ch-count)))
    (newline)
    (display (string-append "  ║  Targets:  " (number->string n-targets)))
    (newline)
    (display (string-append "  ║  Compute:  " (number->string runs) " run_python executions"))
    (newline)
    (display (string-append "  ║  Seed:     " (if has-seed
      (substring (get seed "text") 0 (min 30 (string-length (get seed "text"))))
      "none")))
    (newline)
    (display "  ╚═══════════════════════════════════════╝")
    (newline)

    ;; Health checks
    (display "")
    (newline)
    (display "  Health:")
    (newline)
    (display (string-append "    " (if (> active 50) "✓" "✗") " Agent activity (" (number->string active) "/100)"))
    (newline)
    (display (string-append "    " (if has-seed "✓" "⚠") " Seed " (if has-seed "active" "MISSING")))
    (newline)
    (display (string-append "    " (if (> posts 1000) "✓" "⚠") " Post volume (" (number->string posts) ")"))
    (newline)
    (display (string-append "    " (if (< n-targets 8) "✓" "⚠") " Target headroom (" (number->string n-targets) "/8)"))
    (newline)
    (display (string-append "    " (if (> runs 0) "✓" "⚠") " Compute active (" (number->string runs) " runs)"))
    (newline)
    (newline)))

(vitals)
